## Numpy Built In Functions

## 1. Array Creation Functions

In [1]:
import numpy as np

In [2]:
# Create an array from a list
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [4]:
# Create an array with evenly spaced values
b = np.arange(0,10,2) # # Values from 0 to 10 with step 2
print("array b:", b)

array b: [0 2 4 6 8]


In [5]:
# Create an array with linearly spaced values
c = np.linspace(0,1,5) ## 5 values evenly spaced between 0 and 1
print('array c:', c)

array c: [0.   0.25 0.5  0.75 1.  ]


In [6]:
# Create an array filled with zeros
d = np.zeros((2,3))  # 2x3 array of zeros
print("array d:\n", d)

array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# Create an array filled with ones
e = np.ones((3,2)) # 2x3 array of ones
print("array e:\n", e)

array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
# Create an identity matrix
f = np.eye(4) #4x4 identity matrix
print("4X4 identity matrix f:\n", f)

4X4 identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# Create an identity matrix
f = np.eye(3) #4x4 identity matrix
print("3X3 identity matrix f:\n", f)

4X4 identity matrix f:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Create an identity matrix
f = np.eye(5) #4x4 identity matrix
print("5X5 identity matrix f:\n", f)

5X5 identity matrix f:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 2. Array Manipulation Functions


In [11]:
# Reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))  # Reshape to 1x3
print("reshaped array is:", reshaped)

reshaped array is: [[1 2 3]]


In [12]:
# Flatten an array
f1 = np.array([[1,2],[3,4]])
flatten = np.ravel(f1) ## Flatten to 1D array - Return a contiguous flattened array.
print("Faltten array is:", flatten)

Faltten array is: [1 2 3 4]


In [14]:
# Transpose an array
e1 = np.array([[1,2],[3,4]])
transpose = np.transpose(e1) # return transpose array
print("ranspose array is:\n", transpose)

ranspose array is:
 [[1 3]
 [2 4]]


In [16]:
# Stack arrays vertically
m = np.array([1,2])
n = np.array([3,4])
stacked = np.vstack([m , n]) #Stack arrays in sequence vertically (row wise).
print("Stacked array is:\n", stacked)

Stacked array is:
 [[1 2]
 [3 4]]


## 3. Mathematical Functions


In [17]:
# Add number to the elements of (two) arrays
a = np.array([1,2,3,4])
added = np.add(a, 2) # add to each element of array
print("a added to a:", added)

a added to a: [3 4 5 6]


In [21]:
# Square each element
squared = np.power(a,2) # square each element - First array elements raised to powers from second array, element-wise.
print("square of the array is:", squared)

square of the array is: [ 1  4  9 16]


In [22]:
# Square root of each element
sqrt_val = np.sqrt(a) #Return the non-negative square-root of an array, element-wise.
print("Square root of each element of array:", sqrt_val)

Square root of each element of array: [1.         1.41421356 1.73205081 2.        ]


In [24]:
print(a1)
print(a)

[1 2 3]
[1 2 3 4]


In [26]:
# Dot product of two arrays
a2 = np.array([1,2,3])
dot_product = np.dot(a2, a) #dot product of 2 ararys
print("Dot_Product of 2 array is:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [28]:
# Dot product of two arrays
a2 = np.array([1,2,3,4])
dot_product = np.dot(a2, a) #dot product of 2 ararys
print("Dot_Product of 2 array is:", dot_product)

Dot_Product of 2 array is: 30


In [30]:
a3 = np.array([6,7,8])
dot_product = np.dot(a3, a1) #dot product of 2 ararys
print("Dot_Product of 2 array is:", dot_product)

Dot_Product of 2 array is: 44


## 4. Statistical Functions


In [31]:
s  = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of the array:", mean)

Mean of the array: 2.5


In [32]:
s1  = np.array([10,20,30,40])
mean = np.mean(s1)
print("Mean of the array:", mean)

Mean of the array: 25.0


In [33]:
# Standard deviation of an array
std = np.std(s)
print("Standard deviation:", std)

Standard deviation: 1.118033988749895


In [34]:
# Minimum element of an array
minimum = np.min(s)
print("Minimum element is:", minimum)

Minimum element is: 1


In [35]:
# Maximum element of an array
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


## 5. Linear Algebra Functions


In [36]:
# Create a matrix
mat = np.array([[3,5],[8,9]])
mat

array([[3, 5],
       [8, 9]])

In [38]:
# Determinant of a matrix
determinant = np.linalg.det(mat)
print("Determinant of a matrix:", determinant)

Determinant of a matrix: -13.0


In [39]:
# Inverse of a matrix
inverse = np.linalg.inv(mat)
print("Inverse of a matrix:", inverse)

Inverse of a matrix: [[-0.69230769  0.38461538]
 [ 0.61538462 -0.23076923]]


## 6. Random Sampling Functions


In [40]:
# Generate random values between 0 and 1
ran_vals = np.random.rand(3) ## Array of 3 random values between 0 and 1
print("random values between 0 and 1:", ran_vals)

random values between 0 and 1: [0.43357358 0.81481473 0.68665822]


In [43]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
ran_vals = np.random.rand(3) ## Array of 3 random values between 0 and 1
print("random values between 0 and 1:", ran_vals)

random values between 0 and 1: [0.5488135  0.71518937 0.60276338]


In [45]:
# Set seed for reproducibility
np.random.seed(1)

# Generate random values between 0 and 1
ran_vals = np.random.rand(3) ## Array of 3 random values between 0 and 1
print("random values between 0 and 1:", ran_vals)

random values between 0 and 1: [4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [46]:
# Generate random integers
rand_ints = np.random.randint(0, 15, size=8)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [11  5  0  0  1 12  7 13]


In [49]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 15, size=8)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [12  5  0  3 11  3  7  9]


In [50]:
# Set seed for reproducibility
np.random.seed(1)

# Generate random integers
rand_ints = np.random.randint(0, 15, size=8)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [ 5 11 12  8  9 11  5  0]


## 7. Boolean & Logical Functions


In [51]:
# Check if all elements are True
# all

log_test = np.array([False, True, True])
all_true = np.all(log_test) # Check if all are True
print("All are True:", all_true)

All are True: False


In [52]:
# Check if all elements are True
# all

log_test = np.array([True, True, True])
all_true = np.all(log_test) # Check if all are True
print("All are True:", all_true)

All are True: True


In [54]:
log_test = np.array([False, False, False])
all_false = np.all(log_test) # Check if all are False
print("All are False:", all_false)

All are False: False


In [55]:
log_test = np.array([False, True, False])
any_false = np.any(log_test) # Check if all are False
print("All are False:", any_false)

All are False: True


## 8. Set Operations

In [57]:
# Intersection of two arrays
set_p = np.array([1,2,3,4,5])
set_q = np.array([3,4,5,6,7])
intersec = np.intersect1d(set_p,set_q)
print("Intersection of set_p and set_q is:", intersec)

Intersection of set_p and set_q is: [3 4 5]


In [58]:
# Union of two arrays
union = np.union1d(set_p,set_q)
print("union of set_p and set_q is:", union)

union of set_p and set_q is: [1 2 3 4 5 6 7]


## 9. Array Attribute Functions

In [59]:
# Array attributes

a = np.array([1, 2, 3,4,5])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (5,)
Size of a: 5
Number of dimensions of a: 1
Data type of a: int32


## 10. Other Functions

In [60]:
# Create a copy of an array
c = np.array([1, 2, 3,4])
copied_array = np.copy(c)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3 4]


In [61]:
# Size in bytes of an array
array_size_in_bytes = c.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 16


In [63]:
# Check if two arrays share memory
shared = np.shares_memory(c, copied_array)  # Check if arrays share memory
print("Do c and copied_array share memory?", shared)

Do c and copied_array share memory? False


In [64]:
id(c) == id(copied_array)

False

In [65]:
id(c), id(copied_array)

(2329631438000, 2329631434832)