## What is Numpy?

NumPy (Numerical Python) is a powerful open-source library in Python used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these data structures efficiently.

**Key Features of NumPy:**
+ N-Dimensional Arrays (ndarray) – Fast and efficient multi-dimensional array support.
+ Mathematical Functions – Built-in functions for linear algebra, statistical operations, and more.
+ Broadcasting – Allows arithmetic operations on arrays of different shapes.
+ Performance – Faster computations than Python lists due to optimized C-based implementation.
+ Integration – Works well with other libraries like Pandas, SciPy, and TensorFlow.

In [10]:
import numpy as np

In [11]:
np.__version__

'1.26.4'

In [12]:
import sys
sys.version

'3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:15:57) [MSC v.1916 64 bit (AMD64)]'

## Creating Arrays

In [13]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [14]:
type(my_list)

list

In [16]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [17]:
type(arr)

numpy.ndarray

In [18]:
type(my_list)

list

## Arrange - (Return evenly spaced values within a given interval.)

In [20]:
np.arange(15) # - Create evenly spaced values from 0-14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(3.0)  # - Create evenly spaced float values from 0-2

array([0., 1., 2.])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np.arange(20,10) # In arange function 1st values always less than 2nd value

array([], dtype=int32)

In [29]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [30]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [31]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [32]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [34]:
np.arange(10,10) # In arange function 1st values always less than 2nd value

array([], dtype=int32)

In [35]:
np.arange()

TypeError: arange() requires stop to be specified.

In [36]:
np.arange(10,30,5) # start array from 10 end at 30 with step count of 5

array([10, 15, 20, 25])

In [37]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [38]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

## Zeros - (Return a new array of given shape and type, filled with zeros.)

In [39]:
np.zeros(3)

array([0., 0., 0.])

In [40]:
np.zeros(5, dtype = int) # Create array of 5 zeros with 5 int values

array([0, 0, 0, 0, 0])

In [41]:
np.zeros((2,2), dtype =int)

array([[0, 0],
       [0, 0]])

In [42]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [44]:
zero = np.zeros([2,2])
print(zero)

print('####')
    
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [46]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.zeros([2,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [49]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [51]:
np.zeros((10,30), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [52]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
n = (5,7)
n1 = (5, 9)

In [56]:
print(np.zeros(n1)) # Parameter Tuning

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [55]:
np.zeros(n, dtype = int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [59]:
print(n)
print(n1)

(5, 7)
(5, 9)


In [60]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## One - (Return a new array of given shape and type, filled with ones.)

In [61]:
np.ones (3)

array([1., 1., 1.])

In [62]:
np.ones(5, dtype =int)

array([1, 1, 1, 1, 1])

In [63]:
np.ones(4)

array([1., 1., 1., 1.])

In [64]:
print(n)
print(n1)

(5, 7)
(5, 9)


In [65]:
np.ones(n, dtype =int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [66]:
np.ones(n1, dtype =int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [67]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [68]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [70]:
np.twos(2,6)

AttributeError: module 'numpy' has no attribute 'twos'

In [72]:
np.threes(3,6)

AttributeError: module 'numpy' has no attribute 'threes'

In [73]:
np.ones(2)

array([1., 1.])

In [74]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [76]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

## Range - 

In [77]:
range(0,5)

range(0, 5)

In [78]:
r = range(5)
r

range(0, 5)

In [79]:
for i in r:
    print(i)

0
1
2
3
4


In [80]:
for i in enumerate(r):
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)


In [81]:
list(range(5))

[0, 1, 2, 3, 4]

In [82]:
range(1,10)

range(1, 10)

In [83]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [85]:
list(range(1,20,3)) #list of the elements from 1-20 with step count of 3

[1, 4, 7, 10, 13, 16, 19]

In [86]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

## Rand 

The **rand** function in Python is commonly used from the NumPy library to generate random numbers. It creates an array of random numbers uniformly distributed between 0 and 1.

In [87]:
rand(3,5)

NameError: name 'rand' is not defined

In [88]:
random.rand(4,7)

NameError: name 'random' is not defined

In [89]:
np.random.rand(3,10) #Random Number Generation, rand () - (Random values in a given shape.)

array([[0.28376483, 0.05675946, 0.04962672, 0.3491835 , 0.74241253,
        0.5857093 , 0.85361524, 0.47073456, 0.80921547, 0.83570735],
       [0.69530677, 0.85020113, 0.74639384, 0.09620797, 0.80828527,
        0.57192542, 0.44895739, 0.47400112, 0.01346535, 0.19059091],
       [0.63181931, 0.44702439, 0.54411972, 0.77762736, 0.42539408,
        0.99073573, 0.98189998, 0.53765537, 0.52722784, 0.26243535]])

In [90]:
np.random.rand(3) #Random Number Generation, rand () - (Random values in a given shape.)

array([0.21917895, 0.76464405, 0.38567335])

In [91]:
np.random.rand(2,4)

array([[0.44027024, 0.01407297, 0.99855967, 0.56965528],
       [0.25168987, 0.54486444, 0.60720343, 0.57117788]])

In [92]:
np.random.randint(3,4) #randint -Return random integers from `low` (inclusive) to `high` (exclusive).

3

In [93]:
np.random.randint(2,20) # 2nd argument is exlusive 

11

In [94]:
np.random.randint(10,20,5)

array([19, 16, 12, 18, 11])

In [95]:
np.random.randint(1,6,4)

array([3, 2, 1, 1])

In [96]:
np.random.rand(3)

array([0.81645759, 0.19207798, 0.29510636])

In [97]:
np.random.randint(1)  

0

In [99]:
np.random.randint(30,20,10) # in ranint function 1st values should be always greater than 2nd

ValueError: low >= high

In [100]:
np.random.randint(-30,20,10) 

array([ -4,  15,   8, -27, -24,   5,  11,  18, -10, -19])

In [101]:
np.random.randint(20,30,10) 

array([25, 22, 26, 22, 20, 28, 29, 26, 21, 21])

In [102]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

7

In [103]:
np.random.randint(10,21,3)

array([17, 11, 14])

In [104]:
np.random.randint(1,12,10)

array([ 2, 11,  2,  6, 11,  4,  4,  5,  8,  3])

In [105]:
np.random.randint(10,40,(10,10)) #generre the element 10 -39 with 10*10 mtri

array([[31, 25, 18, 20, 13, 30, 35, 38, 33, 29],
       [17, 25, 35, 33, 32, 20, 30, 34, 25, 24],
       [32, 16, 18, 13, 16, 25, 10, 34, 23, 18],
       [35, 19, 16, 15, 36, 11, 22, 31, 22, 25],
       [15, 32, 25, 31, 24, 30, 28, 34, 28, 19],
       [13, 25, 12, 14, 37, 18, 37, 35, 30, 30],
       [22, 34, 28, 21, 16, 24, 19, 31, 11, 17],
       [21, 36, 11, 39, 30, 24, 14, 11, 11, 14],
       [37, 16, 13, 32, 17, 33, 17, 12, 10, 30],
       [39, 39, 36, 15, 18, 26, 18, 11, 23, 29]])

In [106]:
np.random.randint(1,100,(12,12)) #generre the element 1 - 9 with 12*12 mtri

array([[97, 30, 12, 94,  3, 94, 44, 22, 26, 44, 49, 92],
       [70, 78, 91, 35, 80, 58, 94, 52, 22,  9, 27, 66],
       [39, 43, 87, 88, 54, 68, 53,  9, 96, 56, 75, 24],
       [74, 67, 99, 16, 86, 76, 40, 48,  6, 84, 46, 83],
       [84, 22, 67, 70, 34, 36, 86, 61, 29, 66, 52, 96],
       [86, 23, 25, 22, 86, 80, 51, 65, 22, 33, 77, 57],
       [99,  8, 93, 26, 62, 23, 25, 83, 51, 57, 82, 90],
       [29, 55, 27, 74, 66, 30, 76, 95, 70, 52, 66, 85],
       [96, 45, 30, 95, 51, 60, 19, 84, 77, 85, 21, 66],
       [34, 66, 79, 69, 97, 57, 13, 37, 30, 42, 88, 56],
       [74, 53, 11, 91, 83, 47, 23, 46, 63,  9, 81, 94],
       [60, 88, 39, 40, 56, 19, 56, 47, 36, 83, 62, 48]])

## Reshape - Gives a new shape to an array without changing its data.

In [107]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
np.arange(1,13).reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [109]:
b = np.random.randint(10,20,(5,4))
b

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14],
       [10, 13, 13, 14],
       [13, 12, 15, 10]])

In [110]:
print(type(b))

<class 'numpy.ndarray'>


In [111]:
b

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14],
       [10, 13, 13, 14],
       [13, 12, 15, 10]])

In [112]:
b[:]

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14],
       [10, 13, 13, 14],
       [13, 12, 15, 10]])

In [113]:
b[1:3]

array([[12, 13, 14, 11],
       [18, 19, 12, 14]])

In [114]:
b

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14],
       [10, 13, 13, 14],
       [13, 12, 15, 10]])

In [115]:
b[1,2]

14

In [116]:
b[1,3]

11

In [117]:
b[1,-1]

11

In [118]:
b

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14],
       [10, 13, 13, 14],
       [13, 12, 15, 10]])

In [119]:
b[0:-2]

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14]])

In [120]:
b

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14],
       [10, 13, 13, 14],
       [13, 12, 15, 10]])

In [121]:
b[0,2]

13

In [122]:
b[-5,-3]

19

In [123]:
b

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14],
       [10, 13, 13, 14],
       [13, 12, 15, 10]])

In [124]:
b[-4,2]

14

In [125]:
np.random.randint(10,20,(4,4))

array([[11, 17, 12, 13],
       [17, 13, 17, 17],
       [13, 11, 12, 10],
       [17, 17, 13, 14]])

In [126]:
b

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14],
       [10, 13, 13, 14],
       [13, 12, 15, 10]])

In [127]:
b[-4,-2]

14

In [128]:
b

array([[16, 19, 13, 15],
       [12, 13, 14, 11],
       [18, 19, 12, 14],
       [10, 13, 13, 14],
       [13, 12, 15, 10]])

In [129]:
b[-4:2]

array([[12, 13, 14, 11]])

## Operations

In [133]:
a = np.random.randint(10,20,10)
a

array([15, 17, 15, 11, 19, 17, 13, 18, 19, 11])

In [134]:
id(a)

2101112578256

In [135]:
arr

array([0, 1, 2, 3, 4, 5])

In [136]:
arr1 = np.random.randint(1,100,(10,10))
arr1

array([[ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [79, 90,  5, 63, 24, 30, 32, 39, 94, 96],
       [79, 55, 79, 26, 84, 33, 38, 32, 71, 79]])

In [137]:
arr

array([0, 1, 2, 3, 4, 5])

In [138]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [139]:
arr[0]

0

In [140]:
arr[:4]

array([0, 1, 2, 3])

In [141]:
arr1[:]

array([[ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [79, 90,  5, 63, 24, 30, 32, 39, 94, 96],
       [79, 55, 79, 26, 84, 33, 38, 32, 71, 79]])

In [142]:
arr1[0:5]

array([[ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70]])

In [143]:
arr1

array([[ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [79, 90,  5, 63, 24, 30, 32, 39, 94, 96],
       [79, 55, 79, 26, 84, 33, 38, 32, 71, 79]])

In [145]:
arr1[1,4]

5

In [146]:
arr1

array([[ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [79, 90,  5, 63, 24, 30, 32, 39, 94, 96],
       [79, 55, 79, 26, 84, 33, 38, 32, 71, 79]])

In [147]:
arr1[-5,5]

93

In [148]:
arr1[-5,-5]

93

In [149]:
arr1

array([[ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [79, 90,  5, 63, 24, 30, 32, 39, 94, 96],
       [79, 55, 79, 26, 84, 33, 38, 32, 71, 79]])

In [151]:
arr1[-1,-2]

71

In [153]:
arr1[::-1] #reverse the array

array([[79, 55, 79, 26, 84, 33, 38, 32, 71, 79],
       [79, 90,  5, 63, 24, 30, 32, 39, 94, 96],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90]])

In [154]:
arr1

array([[ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [79, 90,  5, 63, 24, 30, 32, 39, 94, 96],
       [79, 55, 79, 26, 84, 33, 38, 32, 71, 79]])

In [155]:
arr1[::-2]

array([[79, 55, 79, 26, 84, 33, 38, 32, 71, 79],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54]])

In [156]:
arr1[::-3]

array([[79, 55, 79, 26, 84, 33, 38, 32, 71, 79],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90]])

In [157]:
arr1

array([[ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [79, 90,  5, 63, 24, 30, 32, 39, 94, 96],
       [79, 55, 79, 26, 84, 33, 38, 32, 71, 79]])

In [158]:
arr

array([0, 1, 2, 3, 4, 5])

In [160]:
arr.max()

5

In [161]:
arr.min()

0

In [162]:
arr1.max()

98

In [163]:
arr1.min()

1

In [166]:
from numpy import *

In [168]:
arr.mean()

2.5

In [169]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [170]:
from numpy import *

In [171]:
a = array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [172]:
median(a)

2.5

## find the median, mode Without work on import* 

In [173]:
arr

array([0, 1, 2, 3, 4, 5])

In [174]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [175]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [176]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [178]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [179]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [184]:
arr.reshape((2,3),order ='C') ##The array is read and filled row-wise (left to right, top to bottom).

array([[0, 1, 2],
       [3, 4, 5]])

In [185]:
arr.reshape(2,3,order ='C') #C shape

array([[0, 1, 2],
       [3, 4, 5]])

In [186]:
arr.reshape(2,3,order ='F') # # print element with fortran The array is read and filled column-wise (top to bottom, left to right).

array([[0, 2, 4],
       [1, 3, 5]])

In [188]:
arr.reshape(2,3,order ='A') # A - Arbitary # A almost give you c type output Uses 'F' order if the original array is Fortran-contiguous.


array([[0, 1, 2],
       [3, 4, 5]])

In [189]:
arr1

array([[ 5, 80, 46, 43, 54, 75, 51,  2, 72, 90],
       [52, 88, 37, 17,  5, 33, 83, 36, 23, 54],
       [34, 38,  3, 62, 48, 63, 64, 57, 93, 55],
       [ 5, 58, 86, 29,  2, 53, 82, 63, 48, 10],
       [65, 32, 97, 47, 20, 85,  4, 55, 36, 70],
       [81, 18, 76, 21,  3, 93,  8, 98, 29, 75],
       [ 8, 42, 33, 77, 67, 13, 19, 19, 37, 69],
       [92,  3, 44, 41, 37, 86, 26,  1, 30, 12],
       [79, 90,  5, 63, 24, 30, 32, 39, 94, 96],
       [79, 55, 79, 26, 84, 33, 38, 32, 71, 79]])

In [190]:
arr

array([0, 1, 2, 3, 4, 5])

In [191]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [192]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [193]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [194]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [195]:
arr.reshape(2,6) 

ValueError: cannot reshape array of size 6 into shape (2,6)

In [196]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [197]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

## Array Indexing

In [198]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
col = 5
row = 4
print(col)
print(row)

5
4


In [200]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
mat[row,col]

45

In [205]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [206]:
col = 6

In [207]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [208]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [209]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
#with Slicing
mat[:,6] #This means we are extracting all elements from column index 6 across all rows.

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [212]:
mat[row,:] # Exacting 4th row from matrix

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [213]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
mat[:,8] # extacting/selection 8th column from matrix

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [215]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [216]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [217]:
row

4

In [218]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [219]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [220]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [221]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [224]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [225]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
print(col)
print(row)

6
4


In [227]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [228]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [229]:
mat[1,4]

14

In [230]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [231]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [232]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [233]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
mat[8]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [235]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [236]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [237]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [238]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [239]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [240]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [241]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [242]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [244]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [245]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [247]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [248]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [249]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [250]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [251]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [252]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [253]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## Retrive specific matric values from matrix

In [255]:
mat[2:6, 2:4] 

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [256]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [257]:
mat[0:4,1:5]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [258]:
mat[0,1]

1

In [260]:
mat[1,6]

16

In [261]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [263]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [264]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [265]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [266]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [267]:
mat[3,5]

35

In [268]:
mat[1:2,2:4]

array([[12, 13]])

In [270]:
mat[2:3,2:3]

array([[22]])

In [271]:
mat[3:4, 3:4]

array([[33]])

In [272]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [273]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [274]:
mat[3:5, 2:4]

array([[32, 33],
       [42, 43]])

In [275]:
mat[2:3,4:5]

array([[24]])

## Masking (Matrix Filter)

In [276]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [278]:
id(mat)

2101112740272

In [279]:
mat[mat>40]

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])

In [280]:
mat[mat<70]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [282]:
mat[mat==50]

array([50])

In [284]:
mat[mat>=80]

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

In [285]:
mat[mat<=15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Python Program to Generate OTP

In [291]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specific Length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 5034
